name: Deploy to AWS using OIDC

on:
  pull_request:
    branches:
      - staging
    types:
      - closed # Trigger when the PR is closed (merged)

jobs:
  deploy:
    if: github.event.pull_request.merged == true # Only run if the PR was merged
    runs-on: ubuntu-latest

    outputs: # Set job outputs to values from filter step
      frontend: ${{ steps.filter.outputs.frontend }}
    steps:
      - name: Filter code changes
      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            frontend:
              - 'smtalent-react-ecommerce/**'

  frontend: # JOB to build and test frontend code
    needs: deploy
    if: ${{ needs.changes.outputs.frontend == 'true' }}
    runs-on: ubuntu-latest
    defaults:
      run:
        # Frontend folder working directory.
        working-directory: smtalent-react-ecommerce
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      - name: Configure AWS credentials using OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_OIDC_ID }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Execute commands via SSM
        id: execute_command
        run: |
          COMMAND_ID=$(aws ssm send-command \
            --instance-ids ${{ secrets.AWS_INSTANCE_ID }} \
            --document-name "AWS-RunShellScript" \
            --parameters 'commands=["echo "Commands to be executed" ",
                                    "whoami"]' \
            --comment "Deploying comment" \
            --query "Command.CommandId" \
            --output text)

          echo "Command ID: $COMMAND_ID"
          echo "::set-output name=command_id::$COMMAND_ID"

      - name: Output execution via SSM
        id: output_execution
        run: |
          COMMAND_ID=${{ steps.execute_command.outputs.command_id }}
          aws ssm list-command-invocations \
            --details \
            --instance-id ${{ secrets.AWS_EC2_INSTANCE_ID }} \
            --query "CommandInvocations[].CommandPlugins[].{Status:Status,Output:Output}" \
            --command-id "$COMMAND_ID" \
            --output text
